name: steuerung_ek
description: Flutter App fÃ¼r den Einkaufs-Wagen.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sleek_circular_slider: ^2.0.1
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/steeringWheel.png
    - assets/images/gasPedal.png
    - assets/images/Wifi.png

  uses-material-design: true

